### PR TITLE
Implement receiving of team icon

### PR DESCRIPTION
**Pull request by Wouter0100**
Will implement #1. Have tested everything till sending it to Franz using `ipcRenderer`. 

The following line:
```import { ipcRenderer } from 'electron';```

Seem to cause this error:
```
plugin.js:18 SyntaxError: Unexpected token import
    at createScript (vm.js:53)
    at Object.runInThisContext (vm.js:95)
    at Module._compile (module.js:543)
    at Object.Module._extensions..js (module.js:580)
    at Module.load (module.js:488)
    at tryModuleLoad (module.js:447)
    at Function.Module._load (module.js:439)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at EventEmitter.ipcRenderer.on (plugin.js:16)
```

But I am unable to get this working, as it seems to work for Slack. Any help would be appreciated. :+1:

### CODE REVIEW

**Comment by adlk** [comment]
I'm transpiling the recipes with babel. You can simply replace the import with
```js
const { ipcRenderer } = require('electron');
```

I'll add this to the slack recipe as it makes the process just a little bit more complicated than it has to be.

**Comment by Wouter0100** [comment]
Awesome! Thanks. Implemented and works perfect :+1:

**Comment by adlk** [comment]
thanks a lot!

**Comment by Wouter0100** [comment]
Any idea when this could be merged? :smile:

**Review by adlk — APPROVED** [review]

**Comment by adlk** [comment]
@Wouter0100 how about now ;)

**Comment by Wouter0100** [comment]
Awesome, thanks! :confetti_ball:

**Comment by adlk** [comment]
Sorry for the delay, I just missed the PR. 
If this happens in the future, feel free to ping me on Slack after a couple of days.

The update is now deployed. Thanks so much for this nice update.

**Pull request merged**
